# Generated by Django 5.2 on 2025-04-18 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobil',
            fields=[
                ('id_mobil', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('merk', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('tahun', models.PositiveIntegerField()),
                ('harga_dasar', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dana_pinjaman', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('suku_bunga', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_service', models.DateField(auto_now_add=True)),
                ('deskripsi', models.TextField()),
                ('biaya', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mobil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_service', to='showroom.mobil')),
            ],
        ),
    ]
