# Generated by Django 5.2 on 2025-04-19 01:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='tgl_service',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
