# Generated by Django 5.2 on 2025-04-19 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_alter_service_tgl_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobil',
            name='lama_pinjaman',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobil',
            name='pinjaman_lunas',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobil',
            name='tgl_pinjaman',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
