# Generated by Django 5.2 on 2025-04-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0003_mobil_lama_pinjaman_mobil_pinjaman_lunas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='tgl_pinjaman',
            field=models.DateField(blank=True, null=True),
        ),
    ]
